// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp3rCLK2U8vaf8uE_mHDX6NSNLEr18bss',
    appId: '1:22176385837:web:103b37c26fed8fb2df21a4',
    messagingSenderId: '22176385837',
    projectId: 'flutter-web-login-bc8ce',
    authDomain: 'flutter-web-login-bc8ce.firebaseapp.com',
    storageBucket: 'flutter-web-login-bc8ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqS5XZvrQSQfsiLL6xsPG_rzKCVfb5zMM',
    appId: '1:22176385837:android:d01fa6317804b43edf21a4',
    messagingSenderId: '22176385837',
    projectId: 'flutter-web-login-bc8ce',
    storageBucket: 'flutter-web-login-bc8ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ZlevvsW-dDBiwpyNwcvfyeTLGCJBwMU',
    appId: '1:22176385837:ios:96f03fcc91cc155fdf21a4',
    messagingSenderId: '22176385837',
    projectId: 'flutter-web-login-bc8ce',
    storageBucket: 'flutter-web-login-bc8ce.firebasestorage.app',
    iosClientId: '22176385837-r9h0q6r6t4dq8gas79cgpr5pbk2q3dcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellirec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ZlevvsW-dDBiwpyNwcvfyeTLGCJBwMU',
    appId: '1:22176385837:ios:96f03fcc91cc155fdf21a4',
    messagingSenderId: '22176385837',
    projectId: 'flutter-web-login-bc8ce',
    storageBucket: 'flutter-web-login-bc8ce.firebasestorage.app',
    iosClientId: '22176385837-r9h0q6r6t4dq8gas79cgpr5pbk2q3dcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.intellirec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp3rCLK2U8vaf8uE_mHDX6NSNLEr18bss',
    appId: '1:22176385837:web:66c4610838127c78df21a4',
    messagingSenderId: '22176385837',
    projectId: 'flutter-web-login-bc8ce',
    authDomain: 'flutter-web-login-bc8ce.firebaseapp.com',
    storageBucket: 'flutter-web-login-bc8ce.firebasestorage.app',
  );
}
